### ISSUE TITLE
Structure editor number of ring bond constraints for ring atoms

### ISSUE THREAD

**Issue by lithom** [Actelion/openchemlib#104] opened 2023-12-06 14:33 UTC
In the Structure Editor in "Fragment" mode, there is a problem with the "Ring bonds" atom query feature when setting the query feature for atoms that are already contained in a ring. The query feature seems to work correctly for atoms that are not contained in a ring. See e.g. the following example, when opening the atom query features dialog after setting the constraint, the constraint is not shown when reopening the atom dialog:

Video: 
https://github.com/Actelion/openchemlib/assets/38880291/860d08bd-f321-4505-b394-5abb02a02e5e

**Comment by thsa** [comment] 2024-05-01 11:58
thanks for reporting. The issue is now fixed.

**Closed by thsa** 2024-05-01 11:58 UTC
